Drop some unnecessary closure
clippy complains about them so CI is broken because of this:

```
error: unnecessary closure used to substitute value for `Option::None`
   --> src/account.rs:130:30
    |
130 |                 let amount = disputed.amount.ok_or_else(|| Error::MissingAmount)?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: Use `ok_or` instead: `disputed.amount.ok_or(Error::MissingAmount)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
```